### ISSUE TITLE
Add abs function

### ISSUE THREAD

**Issue by chantera** [primitiv/primitiv#185]
Add `abs` function:

```c++
/*
x = {
  1,-2,-3,4,5,
  -2,1,2,-1,0,
};
*/
y = abs(x);
/*
y = {
  1,2,3,4,5,
  2,1,2,1,0,
};
*/
```

**Comment by odashi** [comment]
Which value is chosen for the sub-derivative of abs(0)?

**Comment by chantera** [comment]
The functions of abs(x) is nondifferentiable when x = 0 because the left derivative is -1 and the right derivative is 1.
The sub-derivative of abs(0) is the closed-interval [-1, 1] and the derivative value of abs(0) is chosen from [-1, 1].
In practice, many of NN frameworks use 0 for the (arbitrary) derivative value of abs(0).
I follow this although we can choose another value.
Some people say it does not matter in the context of stochastic gradient descent, but I have little confidence in my understanding of this.
