### ISSUE TITLE
Registering to PyPI

### ISSUE THREAD

**Issue by odashi** [primitiv/primitiv#28]
Good if we could unstall this by `pip install primitiv`.

**Comment by vbkaisetsu** [comment]
`feature/toplevel-setup-py` branch adds `setup.py` that builds both C++ library and python wrapper.
https://github.com/odashi/primitiv/tree/feature/toplevel-setup-py

**Comment by odashi** [comment]
This issue is solved by primitiv/primitiv-python#5.
